<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class EvolutionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"1",
        "pokemon_id_evo"=>"2",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"2",
        "pokemon_id_evo"=>"3",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"4",
        "pokemon_id_evo"=>"5",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"5",
        "pokemon_id_evo"=>"6",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"7",
        "pokemon_id_evo"=>"8",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"8",
        "pokemon_id_evo"=>"9",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"10",
        "pokemon_id_evo"=>"11",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"11",
        "pokemon_id_evo"=>"12",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"13",
        "pokemon_id_evo"=>"14",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"14",
        "pokemon_id_evo"=>"15",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"16",
        "pokemon_id_evo"=>"17",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"17",
        "pokemon_id_evo"=>"18",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"19",
        "pokemon_id_evo"=>"20",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"21",
        "pokemon_id_evo"=>"22",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"23",
        "pokemon_id_evo"=>"24",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"172",
        "pokemon_id_evo"=>"25",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"25",
        "pokemon_id_evo"=>"26",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"27",
        "pokemon_id_evo"=>"28",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"29",
        "pokemon_id_evo"=>"30",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"30",
        "pokemon_id_evo"=>"31",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"32",
        "pokemon_id_evo"=>"33",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"33",
        "pokemon_id_evo"=>"34",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"173",
        "pokemon_id_evo"=>"35",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"35",
        "pokemon_id_evo"=>"36",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"37",
        "pokemon_id_evo"=>"38",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"174",
        "pokemon_id_evo"=>"39",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"39",
        "pokemon_id_evo"=>"40",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"41",
        "pokemon_id_evo"=>"42",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"42",
        "pokemon_id_evo"=>"169",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"43",
        "pokemon_id_evo"=>"44",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"44",
        "pokemon_id_evo"=>"45",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"44",
        "pokemon_id_evo"=>"182",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"46",
        "pokemon_id_evo"=>"47",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"48",
        "pokemon_id_evo"=>"49",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"50",
        "pokemon_id_evo"=>"51",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"52",
        "pokemon_id_evo"=>"53",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"52",
        "pokemon_id_evo"=>"863",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"54",
        "pokemon_id_evo"=>"55",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"56",
        "pokemon_id_evo"=>"57",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"57",
        "pokemon_id_evo"=>"979",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"58",
        "pokemon_id_evo"=>"59",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"60",
        "pokemon_id_evo"=>"61",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"61",
        "pokemon_id_evo"=>"62",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"61",
        "pokemon_id_evo"=>"186",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"63",
        "pokemon_id_evo"=>"64",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"64",
        "pokemon_id_evo"=>"65",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"66",
        "pokemon_id_evo"=>"67",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"67",
        "pokemon_id_evo"=>"68",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"69",
        "pokemon_id_evo"=>"70",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"70",
        "pokemon_id_evo"=>"71",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"72",
        "pokemon_id_evo"=>"73",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"74",
        "pokemon_id_evo"=>"75",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"75",
        "pokemon_id_evo"=>"76",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"77",
        "pokemon_id_evo"=>"78",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"79",
        "pokemon_id_evo"=>"80",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"79",
        "pokemon_id_evo"=>"199",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"81",
        "pokemon_id_evo"=>"82",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"82",
        "pokemon_id_evo"=>"462",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"83",
        "pokemon_id_evo"=>"865",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"84",
        "pokemon_id_evo"=>"85",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"86",
        "pokemon_id_evo"=>"87",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"88",
        "pokemon_id_evo"=>"89",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"90",
        "pokemon_id_evo"=>"91",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"92",
        "pokemon_id_evo"=>"93",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"93",
        "pokemon_id_evo"=>"94",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"95",
        "pokemon_id_evo"=>"208",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"96",
        "pokemon_id_evo"=>"97",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"98",
        "pokemon_id_evo"=>"99",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"100",
        "pokemon_id_evo"=>"101",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"102",
        "pokemon_id_evo"=>"103",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"104",
        "pokemon_id_evo"=>"105",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"236",
        "pokemon_id_evo"=>"106",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"236",
        "pokemon_id_evo"=>"107",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"236",
        "pokemon_id_evo"=>"237",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"108",
        "pokemon_id_evo"=>"463",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"109",
        "pokemon_id_evo"=>"110",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"111",
        "pokemon_id_evo"=>"112",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"112",
        "pokemon_id_evo"=>"464",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"440",
        "pokemon_id_evo"=>"113",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"113",
        "pokemon_id_evo"=>"242",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"114",
        "pokemon_id_evo"=>"465",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"116",
        "pokemon_id_evo"=>"117",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"117",
        "pokemon_id_evo"=>"230",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"118",
        "pokemon_id_evo"=>"119",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"120",
        "pokemon_id_evo"=>"121",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"439",
        "pokemon_id_evo"=>"122",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"122",
        "pokemon_id_evo"=>"866",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"123",
        "pokemon_id_evo"=>"212",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"123",
        "pokemon_id_evo"=>"900",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"238",
        "pokemon_id_evo"=>"124",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"239",
        "pokemon_id_evo"=>"125",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"125",
        "pokemon_id_evo"=>"466",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"240",
        "pokemon_id_evo"=>"126",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"126",
        "pokemon_id_evo"=>"467",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"129",
        "pokemon_id_evo"=>"130",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"134",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"135",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"136",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"196",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"197",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"470",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"471",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"133",
        "pokemon_id_evo"=>"700",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"137",
        "pokemon_id_evo"=>"233",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"233",
        "pokemon_id_evo"=>"474",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"138",
        "pokemon_id_evo"=>"139",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"140",
        "pokemon_id_evo"=>"141",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"446",
        "pokemon_id_evo"=>"143",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"147",
        "pokemon_id_evo"=>"148",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"148",
        "pokemon_id_evo"=>"149",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"152",
        "pokemon_id_evo"=>"153",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"153",
        "pokemon_id_evo"=>"154",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"155",
        "pokemon_id_evo"=>"156",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"156",
        "pokemon_id_evo"=>"157",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"158",
        "pokemon_id_evo"=>"159",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"159",
        "pokemon_id_evo"=>"160",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"161",
        "pokemon_id_evo"=>"162",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"163",
        "pokemon_id_evo"=>"164",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"165",
        "pokemon_id_evo"=>"166",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"167",
        "pokemon_id_evo"=>"168",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"170",
        "pokemon_id_evo"=>"171",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"175",
        "pokemon_id_evo"=>"176",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"176",
        "pokemon_id_evo"=>"468",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"177",
        "pokemon_id_evo"=>"178",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"179",
        "pokemon_id_evo"=>"180",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"180",
        "pokemon_id_evo"=>"181",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"298",
        "pokemon_id_evo"=>"183",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"183",
        "pokemon_id_evo"=>"184",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"438",
        "pokemon_id_evo"=>"185",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"187",
        "pokemon_id_evo"=>"188",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"188",
        "pokemon_id_evo"=>"189",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"190",
        "pokemon_id_evo"=>"424",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"191",
        "pokemon_id_evo"=>"192",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"193",
        "pokemon_id_evo"=>"469",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"194",
        "pokemon_id_evo"=>"195",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"194",
        "pokemon_id_evo"=>"980",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"198",
        "pokemon_id_evo"=>"430",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"200",
        "pokemon_id_evo"=>"429",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"360",
        "pokemon_id_evo"=>"202",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"203",
        "pokemon_id_evo"=>"981",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"204",
        "pokemon_id_evo"=>"205",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"206",
        "pokemon_id_evo"=>"982",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"207",
        "pokemon_id_evo"=>"472",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"209",
        "pokemon_id_evo"=>"210",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"211",
        "pokemon_id_evo"=>"904",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"215",
        "pokemon_id_evo"=>"461",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"215",
        "pokemon_id_evo"=>"903",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"216",
        "pokemon_id_evo"=>"217",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"217",
        "pokemon_id_evo"=>"901",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"218",
        "pokemon_id_evo"=>"219",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"220",
        "pokemon_id_evo"=>"221",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"221",
        "pokemon_id_evo"=>"473",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"222",
        "pokemon_id_evo"=>"864",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"223",
        "pokemon_id_evo"=>"224",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"458",
        "pokemon_id_evo"=>"226",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"228",
        "pokemon_id_evo"=>"229",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"231",
        "pokemon_id_evo"=>"232",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"234",
        "pokemon_id_evo"=>"899",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"246",
        "pokemon_id_evo"=>"247",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"247",
        "pokemon_id_evo"=>"248",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"252",
        "pokemon_id_evo"=>"253",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"253",
        "pokemon_id_evo"=>"254",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"255",
        "pokemon_id_evo"=>"256",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"256",
        "pokemon_id_evo"=>"257",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"258",
        "pokemon_id_evo"=>"259",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"259",
        "pokemon_id_evo"=>"260",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"261",
        "pokemon_id_evo"=>"262",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"263",
        "pokemon_id_evo"=>"264",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"264",
        "pokemon_id_evo"=>"862",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"265",
        "pokemon_id_evo"=>"266",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"266",
        "pokemon_id_evo"=>"267",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"265",
        "pokemon_id_evo"=>"268",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"268",
        "pokemon_id_evo"=>"269",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"270",
        "pokemon_id_evo"=>"271",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"271",
        "pokemon_id_evo"=>"272",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"273",
        "pokemon_id_evo"=>"274",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"274",
        "pokemon_id_evo"=>"275",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"276",
        "pokemon_id_evo"=>"277",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"278",
        "pokemon_id_evo"=>"279",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"280",
        "pokemon_id_evo"=>"281",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"281",
        "pokemon_id_evo"=>"282",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"281",
        "pokemon_id_evo"=>"475",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"283",
        "pokemon_id_evo"=>"284",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"285",
        "pokemon_id_evo"=>"286",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"287",
        "pokemon_id_evo"=>"288",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"288",
        "pokemon_id_evo"=>"289",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"290",
        "pokemon_id_evo"=>"291",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"290",
        "pokemon_id_evo"=>"292",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"293",
        "pokemon_id_evo"=>"294",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"294",
        "pokemon_id_evo"=>"295",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"296",
        "pokemon_id_evo"=>"297",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"299",
        "pokemon_id_evo"=>"476",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"300",
        "pokemon_id_evo"=>"301",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"304",
        "pokemon_id_evo"=>"305",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"305",
        "pokemon_id_evo"=>"306",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"307",
        "pokemon_id_evo"=>"308",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"309",
        "pokemon_id_evo"=>"310",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"406",
        "pokemon_id_evo"=>"315",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"315",
        "pokemon_id_evo"=>"407",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"316",
        "pokemon_id_evo"=>"317",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"318",
        "pokemon_id_evo"=>"319",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"320",
        "pokemon_id_evo"=>"321",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"322",
        "pokemon_id_evo"=>"323",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"325",
        "pokemon_id_evo"=>"326",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"328",
        "pokemon_id_evo"=>"329",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"329",
        "pokemon_id_evo"=>"330",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"331",
        "pokemon_id_evo"=>"332",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"333",
        "pokemon_id_evo"=>"334",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"339",
        "pokemon_id_evo"=>"340",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"341",
        "pokemon_id_evo"=>"342",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"343",
        "pokemon_id_evo"=>"344",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"345",
        "pokemon_id_evo"=>"346",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"347",
        "pokemon_id_evo"=>"348",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"349",
        "pokemon_id_evo"=>"350",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"353",
        "pokemon_id_evo"=>"354",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"355",
        "pokemon_id_evo"=>"356",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"356",
        "pokemon_id_evo"=>"477",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"433",
        "pokemon_id_evo"=>"358",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"361",
        "pokemon_id_evo"=>"362",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"361",
        "pokemon_id_evo"=>"478",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"363",
        "pokemon_id_evo"=>"364",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"364",
        "pokemon_id_evo"=>"365",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"366",
        "pokemon_id_evo"=>"367",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"366",
        "pokemon_id_evo"=>"368",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"371",
        "pokemon_id_evo"=>"372",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"372",
        "pokemon_id_evo"=>"373",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"374",
        "pokemon_id_evo"=>"375",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"375",
        "pokemon_id_evo"=>"376",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"387",
        "pokemon_id_evo"=>"388",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"388",
        "pokemon_id_evo"=>"389",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"390",
        "pokemon_id_evo"=>"391",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"391",
        "pokemon_id_evo"=>"392",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"393",
        "pokemon_id_evo"=>"394",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"394",
        "pokemon_id_evo"=>"395",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"396",
        "pokemon_id_evo"=>"397",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"397",
        "pokemon_id_evo"=>"398",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"399",
        "pokemon_id_evo"=>"400",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"401",
        "pokemon_id_evo"=>"402",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"403",
        "pokemon_id_evo"=>"404",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"404",
        "pokemon_id_evo"=>"405",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"408",
        "pokemon_id_evo"=>"409",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"410",
        "pokemon_id_evo"=>"411",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"412",
        "pokemon_id_evo"=>"413",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"412",
        "pokemon_id_evo"=>"414",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"415",
        "pokemon_id_evo"=>"416",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"418",
        "pokemon_id_evo"=>"419",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"420",
        "pokemon_id_evo"=>"421",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"422",
        "pokemon_id_evo"=>"423",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"425",
        "pokemon_id_evo"=>"426",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"427",
        "pokemon_id_evo"=>"428",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"431",
        "pokemon_id_evo"=>"432",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"434",
        "pokemon_id_evo"=>"435",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"436",
        "pokemon_id_evo"=>"437",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"443",
        "pokemon_id_evo"=>"444",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"444",
        "pokemon_id_evo"=>"445",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"447",
        "pokemon_id_evo"=>"448",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"449",
        "pokemon_id_evo"=>"450",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"451",
        "pokemon_id_evo"=>"452",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"453",
        "pokemon_id_evo"=>"454",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"456",
        "pokemon_id_evo"=>"457",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"459",
        "pokemon_id_evo"=>"460",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"489",
        "pokemon_id_evo"=>"490",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"495",
        "pokemon_id_evo"=>"496",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"496",
        "pokemon_id_evo"=>"497",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"498",
        "pokemon_id_evo"=>"499",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"499",
        "pokemon_id_evo"=>"500",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"501",
        "pokemon_id_evo"=>"502",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"502",
        "pokemon_id_evo"=>"503",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"504",
        "pokemon_id_evo"=>"505",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"506",
        "pokemon_id_evo"=>"507",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"507",
        "pokemon_id_evo"=>"508",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"509",
        "pokemon_id_evo"=>"510",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"511",
        "pokemon_id_evo"=>"512",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"513",
        "pokemon_id_evo"=>"514",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"515",
        "pokemon_id_evo"=>"516",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"517",
        "pokemon_id_evo"=>"518",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"519",
        "pokemon_id_evo"=>"520",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"520",
        "pokemon_id_evo"=>"521",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"522",
        "pokemon_id_evo"=>"523",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"524",
        "pokemon_id_evo"=>"525",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"525",
        "pokemon_id_evo"=>"526",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"527",
        "pokemon_id_evo"=>"528",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"529",
        "pokemon_id_evo"=>"530",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"532",
        "pokemon_id_evo"=>"533",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"533",
        "pokemon_id_evo"=>"534",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"535",
        "pokemon_id_evo"=>"536",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"536",
        "pokemon_id_evo"=>"537",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"540",
        "pokemon_id_evo"=>"541",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"541",
        "pokemon_id_evo"=>"542",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"543",
        "pokemon_id_evo"=>"544",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"544",
        "pokemon_id_evo"=>"545",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"546",
        "pokemon_id_evo"=>"547",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"548",
        "pokemon_id_evo"=>"549",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"550",
        "pokemon_id_evo"=>"902",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"551",
        "pokemon_id_evo"=>"552",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"552",
        "pokemon_id_evo"=>"553",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"554",
        "pokemon_id_evo"=>"555",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"557",
        "pokemon_id_evo"=>"558",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"559",
        "pokemon_id_evo"=>"560",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"562",
        "pokemon_id_evo"=>"563",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"562",
        "pokemon_id_evo"=>"867",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"564",
        "pokemon_id_evo"=>"565",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"566",
        "pokemon_id_evo"=>"567",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"568",
        "pokemon_id_evo"=>"569",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"570",
        "pokemon_id_evo"=>"571",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"572",
        "pokemon_id_evo"=>"573",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"574",
        "pokemon_id_evo"=>"575",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"575",
        "pokemon_id_evo"=>"576",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"577",
        "pokemon_id_evo"=>"578",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"578",
        "pokemon_id_evo"=>"579",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"580",
        "pokemon_id_evo"=>"581",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"582",
        "pokemon_id_evo"=>"583",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"583",
        "pokemon_id_evo"=>"584",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"585",
        "pokemon_id_evo"=>"586",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"588",
        "pokemon_id_evo"=>"589",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"590",
        "pokemon_id_evo"=>"591",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"592",
        "pokemon_id_evo"=>"593",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"595",
        "pokemon_id_evo"=>"596",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"597",
        "pokemon_id_evo"=>"598",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"599",
        "pokemon_id_evo"=>"600",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"600",
        "pokemon_id_evo"=>"601",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"602",
        "pokemon_id_evo"=>"603",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"603",
        "pokemon_id_evo"=>"604",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"605",
        "pokemon_id_evo"=>"606",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"607",
        "pokemon_id_evo"=>"608",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"608",
        "pokemon_id_evo"=>"609",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"610",
        "pokemon_id_evo"=>"611",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"611",
        "pokemon_id_evo"=>"612",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"613",
        "pokemon_id_evo"=>"614",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"616",
        "pokemon_id_evo"=>"617",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"619",
        "pokemon_id_evo"=>"620",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"622",
        "pokemon_id_evo"=>"623",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"624",
        "pokemon_id_evo"=>"625",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"625",
        "pokemon_id_evo"=>"983",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"627",
        "pokemon_id_evo"=>"628",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"629",
        "pokemon_id_evo"=>"630",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"633",
        "pokemon_id_evo"=>"634",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"634",
        "pokemon_id_evo"=>"635",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"636",
        "pokemon_id_evo"=>"637",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"650",
        "pokemon_id_evo"=>"651",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"651",
        "pokemon_id_evo"=>"652",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"653",
        "pokemon_id_evo"=>"654",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"654",
        "pokemon_id_evo"=>"655",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"656",
        "pokemon_id_evo"=>"657",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"657",
        "pokemon_id_evo"=>"658",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"659",
        "pokemon_id_evo"=>"660",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"661",
        "pokemon_id_evo"=>"662",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"662",
        "pokemon_id_evo"=>"663",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"664",
        "pokemon_id_evo"=>"665",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"665",
        "pokemon_id_evo"=>"666",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"667",
        "pokemon_id_evo"=>"668",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"669",
        "pokemon_id_evo"=>"670",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"670",
        "pokemon_id_evo"=>"671",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"672",
        "pokemon_id_evo"=>"673",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"674",
        "pokemon_id_evo"=>"675",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"677",
        "pokemon_id_evo"=>"678",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"679",
        "pokemon_id_evo"=>"680",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"680",
        "pokemon_id_evo"=>"681",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"682",
        "pokemon_id_evo"=>"683",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"684",
        "pokemon_id_evo"=>"685",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"686",
        "pokemon_id_evo"=>"687",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"688",
        "pokemon_id_evo"=>"689",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"690",
        "pokemon_id_evo"=>"691",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"692",
        "pokemon_id_evo"=>"693",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"694",
        "pokemon_id_evo"=>"695",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"696",
        "pokemon_id_evo"=>"697",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"698",
        "pokemon_id_evo"=>"699",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"704",
        "pokemon_id_evo"=>"705",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"705",
        "pokemon_id_evo"=>"706",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"708",
        "pokemon_id_evo"=>"709",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"710",
        "pokemon_id_evo"=>"711",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"712",
        "pokemon_id_evo"=>"713",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"714",
        "pokemon_id_evo"=>"715",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"722",
        "pokemon_id_evo"=>"723",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"723",
        "pokemon_id_evo"=>"724",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"725",
        "pokemon_id_evo"=>"726",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"726",
        "pokemon_id_evo"=>"727",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"728",
        "pokemon_id_evo"=>"729",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"729",
        "pokemon_id_evo"=>"730",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"731",
        "pokemon_id_evo"=>"732",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"732",
        "pokemon_id_evo"=>"733",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"734",
        "pokemon_id_evo"=>"735",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"736",
        "pokemon_id_evo"=>"737",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"737",
        "pokemon_id_evo"=>"738",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"739",
        "pokemon_id_evo"=>"740",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"742",
        "pokemon_id_evo"=>"743",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"744",
        "pokemon_id_evo"=>"745",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"747",
        "pokemon_id_evo"=>"748",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"749",
        "pokemon_id_evo"=>"750",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"751",
        "pokemon_id_evo"=>"752",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"753",
        "pokemon_id_evo"=>"754",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"755",
        "pokemon_id_evo"=>"756",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"757",
        "pokemon_id_evo"=>"758",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"759",
        "pokemon_id_evo"=>"760",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"761",
        "pokemon_id_evo"=>"762",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"762",
        "pokemon_id_evo"=>"763",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"767",
        "pokemon_id_evo"=>"768",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"769",
        "pokemon_id_evo"=>"770",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"772",
        "pokemon_id_evo"=>"773",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"782",
        "pokemon_id_evo"=>"783",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"783",
        "pokemon_id_evo"=>"784",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"789",
        "pokemon_id_evo"=>"790",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"790",
        "pokemon_id_evo"=>"791",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"790",
        "pokemon_id_evo"=>"792",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"803",
        "pokemon_id_evo"=>"804",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"810",
        "pokemon_id_evo"=>"811",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"811",
        "pokemon_id_evo"=>"812",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"813",
        "pokemon_id_evo"=>"814",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"814",
        "pokemon_id_evo"=>"815",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"816",
        "pokemon_id_evo"=>"817",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"817",
        "pokemon_id_evo"=>"818",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"819",
        "pokemon_id_evo"=>"820",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"821",
        "pokemon_id_evo"=>"822",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"822",
        "pokemon_id_evo"=>"823",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"824",
        "pokemon_id_evo"=>"825",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"825",
        "pokemon_id_evo"=>"826",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"827",
        "pokemon_id_evo"=>"828",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"829",
        "pokemon_id_evo"=>"830",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"831",
        "pokemon_id_evo"=>"832",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"833",
        "pokemon_id_evo"=>"834",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"835",
        "pokemon_id_evo"=>"836",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"837",
        "pokemon_id_evo"=>"838",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"838",
        "pokemon_id_evo"=>"839",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"840",
        "pokemon_id_evo"=>"841",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"840",
        "pokemon_id_evo"=>"842",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"840",
        "pokemon_id_evo"=>"1011",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"1011",
        "pokemon_id_evo"=>"1019",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"843",
        "pokemon_id_evo"=>"844",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"846",
        "pokemon_id_evo"=>"847",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"848",
        "pokemon_id_evo"=>"849",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"850",
        "pokemon_id_evo"=>"851",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"852",
        "pokemon_id_evo"=>"853",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"854",
        "pokemon_id_evo"=>"855",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"856",
        "pokemon_id_evo"=>"857",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"857",
        "pokemon_id_evo"=>"858",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"859",
        "pokemon_id_evo"=>"860",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"860",
        "pokemon_id_evo"=>"861",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"868",
        "pokemon_id_evo"=>"869",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"872",
        "pokemon_id_evo"=>"873",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"878",
        "pokemon_id_evo"=>"879",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"884",
        "pokemon_id_evo"=>"1018",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"885",
        "pokemon_id_evo"=>"886",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"886",
        "pokemon_id_evo"=>"887",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"891",
        "pokemon_id_evo"=>"892",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"906",
        "pokemon_id_evo"=>"907",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"907",
        "pokemon_id_evo"=>"908",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"909",
        "pokemon_id_evo"=>"910",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"910",
        "pokemon_id_evo"=>"911",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"912",
        "pokemon_id_evo"=>"913",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"913",
        "pokemon_id_evo"=>"914",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"915",
        "pokemon_id_evo"=>"916",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"917",
        "pokemon_id_evo"=>"918",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"919",
        "pokemon_id_evo"=>"920",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"921",
        "pokemon_id_evo"=>"922",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"922",
        "pokemon_id_evo"=>"923",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"924",
        "pokemon_id_evo"=>"925",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"926",
        "pokemon_id_evo"=>"927",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"928",
        "pokemon_id_evo"=>"929",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"929",
        "pokemon_id_evo"=>"930",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"932",
        "pokemon_id_evo"=>"933",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"933",
        "pokemon_id_evo"=>"934",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"935",
        "pokemon_id_evo"=>"936",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"935",
        "pokemon_id_evo"=>"937",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"938",
        "pokemon_id_evo"=>"939",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"940",
        "pokemon_id_evo"=>"941",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"942",
        "pokemon_id_evo"=>"943",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"944",
        "pokemon_id_evo"=>"945",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"946",
        "pokemon_id_evo"=>"947",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"948",
        "pokemon_id_evo"=>"949",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"951",
        "pokemon_id_evo"=>"952",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"953",
        "pokemon_id_evo"=>"954",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"955",
        "pokemon_id_evo"=>"956",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"957",
        "pokemon_id_evo"=>"958",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"958",
        "pokemon_id_evo"=>"959",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"960",
        "pokemon_id_evo"=>"961",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"963",
        "pokemon_id_evo"=>"964",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"965",
        "pokemon_id_evo"=>"966",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"969",
        "pokemon_id_evo"=>"970",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"971",
        "pokemon_id_evo"=>"972",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"974",
        "pokemon_id_evo"=>"975",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"996",
        "pokemon_id_evo"=>"997",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"997",
        "pokemon_id_evo"=>"998",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"999",
        "pokemon_id_evo"=>"1000",
    ]);
    DB::table("Evolutions")->insert([
        "pokemon_id"=>"1012",
        "pokemon_id_evo"=>"1013",
    ]);
          
    }
}
